// This file is auto-generated by scripts/setup-hubspot-forms.js
// Run `node scripts/setup-hubspot-forms.js` once to populate the real form IDs.
// Until then, forms will show a "form not configured" placeholder.

export const HUBSPOT_PORTAL_ID = "243871292";

export const HUBSPOT_FORM_IDS = {
  CONTACT:     "REPLACE_WITH_FORM_ID",
  MEMBERSHIP:  "REPLACE_WITH_FORM_ID",
  SUBSCRIBE:   "REPLACE_WITH_FORM_ID",
  PARTNERSHIP: "REPLACE_WITH_FORM_ID",
};
