// Auto-generated by scripts/setup-hubspot-forms.js
// Do not edit by hand – re-run the script to regenerate.

export const HUBSPOT_PORTAL_ID = "243871292";

export const HUBSPOT_FORM_IDS = {
  CONTACT:     "26c51ffa-691a-455a-b326-2332e072724b",
  MEMBERSHIP:  "bb888823-ca3c-4446-b1b6-0391d00f8a7c",
  SUBSCRIBE:   "c4e048b0-20d2-4774-88aa-55c1051587c6",
  PARTNERSHIP: "2c33e0df-0db6-4be2-9eab-e52eac2af84d",
};
